site_name: Документация ClinicCore

site_url: https://TheTrueKingM.github.io/ClinicSolution-Learning/

repo_url: https://github.com/TheTrueKingM/ClinicSolution-Learning

repo_name: GitHub Repo

theme:
  name: material
  language: ru

  features:
    - navigation.expand
    - content.code.copy

nav:
  - Главная: index.md

  - Руководство пользователя:
      - Быстрый старт: user-guide/getting-started.md
      - Словарь терминов: user-guide/glossary.md

  - Разработчику:
      - Архитектура: developer/architecture.md
      - API: developer/api.md
